export const routes = (history: any) => [
	{
		name: 'General',
		route: ['/admin/settings/general'],
		icon: '/images/siderbar-icons/settings-outline.svg',
		img: true,
		click: () => history.push('/admin/settings/general'),
	},
	{
		name: 'Notifications',
		route: ['/admin/settings/notifications'],
		icon: '/images/siderbar-icons/notification.svg',
		img: true,
		click: () => history.push('/admin/settings/notifications'),
	},
	{
		name: 'Privacy',
		route: ['/admin/settings/privacy'],
		icon: '/images/siderbar-icons/finger-print-outline.svg',
		img: true,
		click: () => history.push('/admin/settings/privacy'),
	},
	{
		name: 'Security',
		route: ['/admin/settings/security'],
		icon: '/images/siderbar-icons/shield-outline.svg',
		img: true,
		click: () => history.push('/admin/settings/security'),
	},
	{
		name: 'Add New Executive',
		route: ['/admin/settings/new-executive'],
		icon: '/images/siderbar-icons/person.svg',
		img: true,
		click: () => history.push('/admin/settings/new-executive'),
	},
	{
		name: 'Get Paid',
		route: ['/admin/settings/get-paid'],
		icon: '/images/siderbar-icons/get-paid.svg',
		img: true,
		click: () => history.push('/admin/settings/get-paid'),
	},
	{
		name: 'Tax Information',
		route: ['/admin/settings/tax-information'],
		icon: '/images/siderbar-icons/tax-information.svg',
		img: true,
		click: () => history.push('/admin/settings/tax-information'),
	},
	// {
	//     name: 'Transaction History',
	//     route: ['/user/settings/transaction'],
	//     icon: '/images/siderbar-icons/transaction.svg',
	//     img: true,
	//     click: () => history.push('/user/settings/transaction'),
	// },

	// {
	//     name: 'Personal Data',
	//     route: ['/user/settings/personal-data'],
	//     icon: '/images/siderbar-icons/person.svg',
	//     img: true,
	//     click: () => history.push('/user/settings/personal-data'),
	// },
	// {
	//     name: 'Account Action',
	//     route: ['/user/settings/account-action'],
	//     icon: '/images/siderbar-icons/accAction.svg',
	//     img: true,
	//     click: () => history.push('/user/settings/account-action'),
	// },
	// {
	//   name: "General",
	//   route: ["/user/settings/general"],
	//   icon: "/template/user/siderbar-icons/settings-outline.png",
	//   img: true,
	//   click: () => history.push("/user/settings/general"),
	// },
	// {
	//   name: "Notification",
	//   route: ["/user/settings/notification"],
	//   icon: "/template/user/siderbar-icons/notification.png",
	//   img: true,
	//   click: () => history.push("/user/settings/notification"),
	// },
	// {
	//   name: "Contributors",
	//   route: ["/user/settings/contributors"],
	//   icon: "/template/user/siderbar-icons/Paticipatation.png",
	//   img: true,
	//   click: () => history.push("/user/settings/contributors"),
	// },
	// {
	//   name: "GetPaid",
	//   route: ["/user/settings/get-paid"],
	//   icon: "/template/user/siderbar-icons/get-paid.png",
	//   img: true,
	//   click: () => history.push("/user/settings/get-paid"),
	// },
	// {
	//   name: "TaxInformation",
	//   route: ["/user/settings/tax-information"],
	//   icon: "/template/user/siderbar-icons/taxes.png",
	//   img: true,
	//   click: () => history.push("/user/settings/tax-information"),
	// },
	// {
	//   name: "Transaction History",
	//   route: ["/user/settings/transaction"],
	//   icon: "/template/user/siderbar-icons/transaction.png",
	//   img: true,
	//   click: () => history.push("/user/settings/transaction"),
	// },
	// {
	//   name: "Privacy",
	//   route: ["/user/settings/privacy"],
	//   icon: "/template/user/siderbar-icons/finger-print-outline.png",
	//   img: true,
	//   click: () => history.push("/user/settings/privacy"),
	// },
	// {
	//   name: "Security",
	//   route: ["/user/settings/security"],
	//   icon: "/template/user/siderbar-icons/shield-outline.png",
	//   img: true,
	//   click: () => history.push("/user/settings/security"),
	// },
	// {
	//   name: "PersonalData",
	//   route: ["/user/settings/personal-data"],
	//   icon: "/template/user/siderbar-icons/user.png",
	//   img: true,
	//   click: () => history.push("/user/settings/personal-data"),
	// },
	// {
	//   name: "AccountAction",
	//   route: ["/user/settings/account-action"],
	//   icon: "/template/user/siderbar-icons/account-action.png",
	//   img: true,
	//   click: () => history.push("/user/settings/account-action"),
	// },
];
