#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Fomatting and testing project before committing'

# Check Prettier standards
yarn check-format ||
(
    echo '🤢🤮 Its FOKING RAW - Your code formatting looks disgusting. 🤮🤢
    Prettier Check Failed. Run "yarn format" or "npm run format" to format all of the files (excluded files from .prettierignore), add changes and try commit again. Or to format specific files, Run "npm run formatFiles <path/file-name> <path/file-name>", add changes and try commit again.'
    false;
)

echo '✅... Passed Formatting Check...'

# Check ESLint Standards
yarn lint ||
(
    echo '❌ ESLint Check Failed. 
    Make the required changes listed above, add changes and try to commit again.'
    false; 
)

echo '✅ ✅... Passed ESLint Check...'

# Check tsconfig standards
yarn type-check ||
(
    echo '❌❌ Failed Type check. 
    Are you seriously trying to write that? Make the changes required above.'
    false;
)

# If everything passes... Now we can commit
echo '✅ ✅ ✅... Passed Type Check... 
...Alright.... Your Code looks good :)... Committing changes now.'